######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 11 20:52:53 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += board.h brute.h fast.h main_window.h point.h point_plotter.h
SOURCES += board.cpp main.cpp main_window.cpp
