all: main_rand main_deque Subset Palindrome

main_rand: main_rand.cpp randomized_queue.h

main_deque: main_deque.cpp deque.h

Subset: Subset.cpp randomized_queue.h

Palindrome: Palindrome.cpp deque.h

clean:
	rm main_rand main_deque Subset Palindrome